### ISSUE TITLE
Project has active maintenance ?

### ISSUE THREAD

**Issue by vkuehn** [fpgmaas/cookiecutter-poetry#109]
**Question**
The project looks really interesting so I wonder why not more issues has been raised.

e.g. python 3.9 is pretty old now addays.

the renovate pr has been already been raised.

Is the project actively beeing maintained ?

**Comment by fpgmaas** [comment]
I am not actively working on the project :) But I am always open for PR's. 

Python 3.9 is a bit old, but not [EOL](https://devguide.python.org/versions/).
