### ISSUE TITLE
Extra F inserted into user email?

### ISSUE THREAD

**Issue by szvsw** [fpgmaas/cookiecutter-poetry#123]
https://github.com/fpgmaas/cookiecutter-poetry/blob/7d8b270bd9b32e1cdaa0f28cfe488513dd6151f1/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L5

Unless I am missing something weird, the f should not be there.

see e.g.

https://python-poetry.org/docs/pyproject/#authors

**Comment by fpgmaas** [comment]
Oops, that should not be there indeed! Thanks for raising this.
