### ISSUE TITLE
Return error 1

### ISSUE THREAD

**Issue by soulraven** [fpgmaas/cookiecutter-poetry#34]
When the workflow runs is returning error 1 and fails

`make: *** [Makefile:28: lint] Error 1
Error: Process completed with exit code 2.`

https://github.com/fpgmaas/cookiecutter-poetry/blob/ad824f0d4c820081377cea04098bfd14aeade2e1/Makefile#L21

some discussions are here:
https://github.com/PyCQA/isort/issues/1039

**Comment by fpgmaas** [comment]
Thanks for opening an issue! It seems like the proposed solution there is to add the `--check-only` flag together with the `--diff` flag, which is what we are doing here.

Is the error you see really unexpected behavior? Did you try running `make format` locally? Let me know if I am overlooking something!

**Comment by soulraven** [comment]
hello,
is irony is that locally is working just fine, but after i push the code and action runs, throws this error.
meaby a redirect to null?

**Comment by fpgmaas** [comment]
I think you are talking about [this repository](https://github.com/soulraven/roundbox), right? It seems that it's applying `isort` to the `.venv` folder. There's some things wrong with your set-up:

- I see that you configured `isort` both in a `cfg` file, and in your `pyproject.toml`. You should remove `isort.cfg`.
- remove this line from pyproject.toml: `skip = ["{{roundbox.project_name}}",".venv"]` You don't need the first one, that folder does not exist; I believe you copied that from my cookiecutter repository, which does have a directory with the literal name `{{cookiecutter.project_name}}`.

**Comment by soulraven** [comment]
yes, that is the repository, i try to make a GitHub workflow. The code is in the making.
Thx for the isort.cfg is somehow legacy from a local test.

i will test right now to see if it fails again
