### ISSUE TITLE
Feature Request: coverage report as GHA

### ISSUE THREAD

**Issue by ygworldr** [fpgmaas/cookiecutter-poetry#48]
**Is your feature request related to a problem? Please describe.**

I would like to see a coverage report generated by the unit tests. Clearly, this will have to happen to only the latest (?) python version.

**Describe the solution you would like**

We could use [this GitHub action](https://github.com/romeovs/lcov-reporter-action).

This takes an `coverage.lcov` report, which coverage can generate via `coverage lcov`. The latest (or supported) version of Python within tox could generate it.

**Additional context**

I am not attached to [this GitHub action](https://github.com/romeovs/lcov-reporter-action) at all, so if there is something else, that would work too.

**Comment by fpgmaas** [comment]
I like the suggestion, it's something I have considered adding in the past as well. I have not gotten around to it though, and I might not for a while due to a recent career switch. In the meantime, I am always open to PR's that add the functionality.

**Comment by fpgmaas** [comment]
Sorry that it took a while, but it should now be included in release [0.3.9](https://github.com/fpgmaas/cookiecutter-poetry/releases/tag/0.3.9). If you have the time, please give it a try and let me know if this is what you had in mind when you requested the enhancement. See it in use [here[(https://github.com/fpgmaas/cookiecutter-poetry-example) or in my new project; [deptry](https://github.com/fpgmaas/deptry)
