### ISSUE TITLE
Add Gitlab CI/CD option

### ISSUE THREAD

**Issue by fpgmaas** [fpgmaas/cookiecutter-poetry#5]

**Comment by fpgmaas** [comment]
Done.

**Comment by austinmw** [comment]
How do we use the GitLab CI/CD?

Also is there a way to replace all the GitHub links with GitLab links?

**Comment by fpgmaas** [comment]
@austinmw Sorry, that is currently not something that is supported. This issue is from the very early stages of development, and I recall deciding against it because it became a bit complex to handle (and maintain) both Gitlab and GitHub pipelines. I don't think I ever implemented Gitlab. Sorry for the confusing comment above :) I am afraid that to use Gitlab CI you'd have to delete the .github directory and add a `.gitlab-ci.yml` yourself.
