### ISSUE TITLE
Broken on-release-main.yml when publish_to = none and cookiecutter.mkdocs = n

### ISSUE THREAD

**Issue by aaccioly-mpn** [fpgmaas/cookiecutter-poetry#78]
As per title, when one initialises a project with

    include_github_actions: y
    cookiecutter.mkdocs: n
    publish_to: none

Cookiecutter generates a on-release-main file with no steps, which fails the build.

Suggested solutions:

Either remove the file all together when `publish_to: none` or execute all steps until the actual publishing.

**Comment by fpgmaas** [comment]
Thanks for raising the issue! I will look into this.
