### ISSUE TITLE
Is the gh-pages branch for MkDocs supposed to be created manually?

### ISSUE THREAD

**Issue by ariffjeff** [fpgmaas/cookiecutter-poetry#83]
**Question**

I'm trying to setup a new project and noticed that a `gh-pages` branch wasn't created automatically at any point for making auto MkDocs possible. The [documentation](https://fpgmaas.github.io/cookiecutter-poetry/features/mkdocs/#documentation-with-mkdocs) doesn't specify when/how the branch is created so I've become a bit confused on whether or not I was supposed to create it myself and then run a specific `make` command or similar to get the docs published on the remote repo. What are the proper steps here? Thanks!

**Comment by fpgmaas** [comment]
Thanks for raising this! I will update the documentation to better reflect what's happening.
