### ISSUE TITLE
Add Devcontainer/Codespaces Specifications

### ISSUE THREAD

**Issue by kenibrewer** [fpgmaas/cookiecutter-poetry#94]
**Describe the solution you would like**

Devcontainer specifications provide a reproducible environment with pre-installed software dependencies. They make it easier for new contributors / collaborators to jump into a project and make contributions instead of spending time setting up their dev environment.  

**Additional context**

If this feature is of interest, I would be willing to contribute the necessary code.

**Comment by fpgmaas** [comment]
Hi @kenibrewer, thanks for the suggestion! I see devcontainers being used more and more around me in the companies I work for, so I'd fully support this feature. I look forward to your contribution and I will try to review quickly once you have a proposal!
